@startuml RegisterUser

actor Guest as guest
participant QQApp as qq
participant API as api
participant UserEmail as email
guest->guest: Register form\nProvides necessary information (1)
guest->guest: Validates "I'm Not a Robot"
guest->qq: Submits information
qq->api: Sends submited information\nother api required information
qq->guest: Send message to check email
api->api: Validates information provided (2)
api->api: Generate unique identifiers (3)\napi->api: Creates User Registration record in \nstatus 'Waiting Validation'
api->qq: Send response with the identifiers\nand acceptance information
qq->qq: Generate link with the identifiers provided by the API
qq->email: email link with the query string (4)
guest->email:Go to email and navigate to link
guest->qq: Link directs guest to App
qq->qq: Get query string
qq->api: Send query string info\nother api required information
api->api: Validates information
api->api: updates User Registration record in \nstatus 'Validated'
api->api: Generates registration  token
api->qq: sends token and some user information
qq->qq: Generates login cookies with the info provided
qq->guest: Redirects Guest to its User Dashboard\nAnd provides required cookies to keep\nuser authenticated
note right of guest : Guest is now registered\nand authenticated

@enduml